[build]
  publish = "dist/"
  command = "npm run build"

[[redirects]]
# Redirect default Netlify subdomain to primary domain
  from = "https://joshingmachine.netlify.com/*"
  to = "https://www.joshingmachine.com/:splat"
